songs = [{'title': 'Bohemian Rhapsody', 'artist': 'Queen', 'genre': 'Rock'},
        {'title': 'Imagine', 'artist': 'John Lennon', 'genre': 'Pop'},
        {'title': 'Hotel California', 'artist': 'Eagles', 'genre': 'Rock'},
        {'title': 'Billie Jean', 'artist': 'Michael Jackson', 'genre': 'Pop'},
        {'title': 'Smells Like Teen Spirit', 'artist': 'Nirvana', 'genre': 'Grunge'},
        {'title': 'Like a Rolling Stone', 'artist': 'Bob Dylan', 'genre': 'Folk Rock'},
        {'title': 'What\'s Going On', 'artist': 'Marvin Gaye', 'genre': 'Soul'},
        {'title': 'Stairway to Heaven', 'artist': 'Led Zeppelin', 'genre': 'Rock'},
        {'title': 'Purple Haze', 'artist': 'Jimi Hendrix', 'genre': 'Rock'},
        {'title': 'Respect', 'artist': 'Aretha Franklin', 'genre': 'Soul'},
        {'title': 'Good Vibrations', 'artist': 'The Beach Boys', 'genre': 'Pop'},
        {'title': 'Hey Jude', 'artist': 'The Beatles', 'genre': 'Pop'},
        {'title': 'Superstition', 'artist': 'Stevie Wonder', 'genre': 'Funk'},
        {'title': 'What\'d I Say', 'artist': 'Ray Charles', 'genre': 'R&B'},
        {'title': 'Whole Lotta Love', 'artist': 'Led Zeppelin', 'genre': 'Rock'},
        {'title': 'Every Breath You Take', 'artist': 'The Police', 'genre': 'Rock'},
        {'title': 'I Want to Hold Your Hand', 'artist': 'The Beatles', 'genre': 'Pop'},
        {'title': 'Born to Run', 'artist': 'Bruce Springsteen', 'genre': 'Rock'},
        {'title': 'Boogie Wonderland', 'artist': 'Earth, Wind & Fire', 'genre': 'Disco'},
        {'title': 'I Will Always Love You', 'artist': 'Whitney Houston', 'genre': 'Pop'}]